version: '3'
services:
  web:
    container_name: strapiexample
    env_file: .env
    build: .
    command: npm run develop
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '1337:1337'
    restart: always
